# weights_path: "weights/20250115best.pt"
# weights_path: "weights/best_ba.pt"
# weights_path: "weights/best.pt"
weights_path: "../weights/best.pt/"
weights_path_shoot: "../weights/03102025_best.pt/"

classes: ["ball", "rim", "made"]
classes_shoot: ["ball", "person", "rim", "shoot"]

# input: "uploads/nba1.mp4"
# input: "uploads/nba1.mp4"
# input: 'uploads/amateur2.mp4'
input: "video3.mp4"
# input: "/home/fyp_gch6/jason/testing_video/nba_3.mp4"
# input: "/home/fyp_gch6/jason/testing_video/amateur_clean_low.mp4"
# input: "/home/fyp_gch6/jason/data_gen_vids/hl_prof_2_converted.mp4"
# input: "/home/fyp_gch6/jason/data_gen_vids/hl_ama_la_2.mp4"
# input: "/home/fyp_gch6/jason/data_gen_vids/jch.mp4"
# input: "uploads/VIDEO-2025-04-07-16-26-55.mp4"
# input: "/home/fyp_gch6/jason/testing_video/hl_prof_1_cut.mp4"
# input: "/home/fyp_gch6/jason/testing_video/fix_cam.mp4"

save_video: True
output_path: "output"
upload_path: "uploads"
data_path: "data"
report_path: "reports"
resource_path: "resources"
output_width: 1280
output_height: 720
iou_threshold: 0.4
screenshot_path: "screenshots"
screenshot: False
flask_port: 5555
device: 'cpu'
